# Generated by Django 4.0.6 on 2022-08-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='number',
            field=models.IntegerField(blank=True, default=0, verbose_name='nunber'),
        ),
    ]
